### ISSUE TITLE
prevent access from the internet?

### ISSUE THREAD

**Issue by thisIsLoading** [artmizu/nuxt-prometheus#34]
hi,
maybe i am doing it wrong but could it be that /metrics is exposed to the internet? if so, is there a way to prevent that? i thought about a nuxt middleware but it seems that the metrics endpoint is intercepted way earlier, before getting to nuxt and therefore ignoring the middleware.

did i miss a setting?

**Comment by artmizu** [comment]
> hi, maybe i am doing it wrong but could it be that /metrics is exposed to the internet? if so, is there a way to prevent that? i thought about a nuxt middleware but it seems that the metrics endpoint is intercepted way earlier, before getting to nuxt and therefore ignoring the middleware.
> 
> did i miss a setting?

hi
i usually did it via HTTP server, Nginx for example. Because overall question is about the network and accessibility of certain routes across it

**Comment by thisIsLoading** [comment]
hey, wow, thank you for that quick response!

yeah, i somehow hadnt that easy idea. thanks for bringing it up.

for future travelers:
mine runs in a kubernetes cluster with traefik as proxy. have configured a middleware like this:

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: block-metrics
  namespace: your-namespace
spec:
  replacePathRegex:
    regex: ^/metrics
    replacement: /
```

works great.
